Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2018-06, with the labels that each got.

#811 upgrade to spring io platform Cairo-SR1. #810
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress, version: 5.5.0

#817 Revert "upgrade to tomcat v9.0.6 #810"
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress

#818 Revert "upgrade to spring io platform Cairo-SR1. #810"
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress

#820 [5.5.0.RC2]Upgrade to spring io platform Cairo-SR1. #810
  .travis.yml
  terasoluna-gfw-common-libraries/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/ExceptionLoggerTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/ResultMessagesLoggingInterceptorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/message/MessagesPanelTagTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/exception/HandlerExceptionResolverLoggingInterceptorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/HttpSessionEventLoggingListenerTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/mvc/support/CompositeRequestDataValueProcessorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenInterceptorTest.java
  terasoluna-gfw-parent/pom.xml
Labels: 5.5.0.RC2, status: in-progress

#821 [5.5.0.RC2]Upgrade to MyBatis #813
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress, version: 5.5.0

#824 [5.5.0.RC2] Upgrade to dozer v6.2.0 #823
  terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress

#826 update to 5.5.0.RC2-SNAPSHOT #825
  pom.xml
  terasoluna-gfw-common-libraries/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
  terasoluna-gfw-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress
