Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2019-04, with the labels that each got.

#890 remove dependency of jcl-over-slf4j #889
  terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
Labels: type: improvement, version: 5.6.0

#895 [5.4.x] Unify target of constraint annotations #857
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/ConsistOf.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
Labels: type: improvement, version: 5.4.2

#894 [5.4.x] new feature reloadable i18n codelist #11
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeListTest.java
Labels: type: new-feature, version: 5.4.2

#903 [5.4.2.RELEASE] Downgrade Tomcat version -> 8.5.38 #902
  terasoluna-gfw-parent/pom.xml
Labels: version: 5.4.2

#908 [5.4.2.RELEASE]update tomcat version 8.5.40 #907
  terasoluna-gfw-parent/pom.xml
Labels: version: 5.4.2
