Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2019-03, with the labels that each got.

#837 Move dependency jackson-datatype-joda to gfw-jodatime-dependencies #736
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
Labels: status: in-progress

#876 [5.4.x]move dependency jacson-datatype-joda to gfw-jodatime-dependencies #736 (#837)
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
Labels: status: in-progress

#874 add default locale resolve function #363
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/i18n/simpleI18nCodeList.xml
Labels: status: in-progress, type: new-feature, version: 5.5.1

#878 fix typo #761
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/main/java/org/terasoluna/gfw/common/validator/constraintvalidators/ByteSizeValidator.java
Labels: status: in-progress, type: misc, version: 5.5.1

#879 @ExistInCodeList enable to validate Number #877
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidator.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForNumber.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
Labels: status: in-progress, type: improvement, version: 5.5.1

#880 remove deprecated hibernate-entitymanager #875
  terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
Labels: status: in-progress, type: improvement, version: 5.5.1

#881 make reloadable codelist immutable #809
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/AbstractReloadableCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapper.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapperTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
Labels: status: in-progress, type: bug, version: 5.5.1

#882 new feature reloadable i18n codelist #11
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/AbstractI18nCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeListTest.java
Labels: status: in-progress, type: new-feature, version: 5.5.1

#883 change @since version to 5.4.2 #809 #11
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/ReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/i18n/SimpleReloadableI18nCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
Labels: status: in-progress, type: misc, version: 5.5.1

#884 adjust testcase signature #761
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMaxTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraints/ByteMinTest.java
Labels: status: in-progress, type: misc, version: 5.5.1

#886 [5.4.x] resolve using deprecated API #872
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0201_Katakana.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0201_LatinLetters.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_BoxDrawingChars.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_CyrillicLetters.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_GreekLetters.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_Hiragana.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_Katakana.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_LatinLetters.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_Kanji.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0213_Kanji.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/CodePoints.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/ASCIIControlChars.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/ASCIIPrintableChars.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/CRLF.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/catalog/ABCD.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/catalog/AbstractCodePoints.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/catalog/IllegalCodePoints.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/AtoF.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/AtoL.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/test/java/org/terasoluna/gfw/common/codepoints/validator/GtoL.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/AbstractReloadableCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidatorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/exception/test/TestService.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/message/ResultMessageTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/AbstractDateFactoryTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/DefaultDateFactoryTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/JdbcAdjustedDateFactoryTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/src/test/java/org/terasoluna/gfw/common/date/JdbcFixedDateFactoryTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/main/java/org/terasoluna/gfw/common/fullhalf/FullHalfPair.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-string/src/test/java/org/terasoluna/gfw/common/fullhalf/FullHalfPairTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/src/test/java/org/terasoluna/gfw/common/validator/constraintvalidators/ConstraintValidatorsUtilsTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/message/MessagesPanelTagTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/Functions.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/FunctionsTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/TraceLoggingInterceptorTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/logging/mdc/XTrackMDCPutFilterTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/token/transaction/TransactionTokenContextImplTest.java
Labels: status: in-progress, type: improvement, version: 5.4.2

#887 [5.4.x] @ExistInCodeList enable to validate Number #877
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ExistInCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/NumberRangeCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/AbstractExistInCodeListValidator.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/validator/ExistInCodeListValidatorForNumber.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ExistInCodeListTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/resources/org/terasoluna/gfw/common/codelist/ExistInCodeListTest-context.xml
Labels: type: improvement, version: 5.4.2

#888 [5.4.x] make reloadable codelist immutable #809
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/AbstractReloadableCodeList.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapper.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/codelist/ReadWriteLockMapWrapperTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/codelist/CodeListInterceptor.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/codelist/CodeListInterceptorTest.java
Labels: type: bug, version: 5.4.2
