Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2019-01, with the labels that each got.

#856 Upgrade to Spring IO platform Brussels-SR15 #849
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress, version: 5.4.2

#861 apply spring boot dependencies 2.1.2, mybatis 3.5.0 #858 #859 #860
  .travis.yml
  ISSUE_TEMPLATE.md
  pom.xml
  terasoluna-gfw-common-libraries/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0201/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208/src/main/java/org/terasoluna/gfw/common/codepoints/catalog/JIS_X_0208_SpecialChars.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0208kanji/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/catalog/terasoluna-gfw-codepoints-jisx0213kanji/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-jodatime/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-security-web/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-string/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-validator/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/pom.xml
  terasoluna-gfw-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-common-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jodatime-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-mybatis3-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-recommended-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-recommended-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-security-core-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-security-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-web-dependencies/pom.xml
  terasoluna-gfw-dependencies/terasoluna-gfw-web-jsp-dependencies/pom.xml
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress, type: new-feature, version: 5.6.0

#865 fix javadoc errors for jdk11 #864
  .travis.yml
  terasoluna-gfw-common-libraries/pom.xml
  terasoluna-gfw-common-libraries/terasoluna-gfw-codepoints/src/main/java/org/terasoluna/gfw/common/codepoints/CodePoints.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessage.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/message/ResultMessages.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/main/java/org/terasoluna/gfw/common/query/LikeConditionEscape.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/message/MessagesPanelTag.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
Labels: status: in-progress, type: bug, version: 5.5.1

#866 update google guava 27.0.1-jre #862
  terasoluna-gfw-parent/pom.xml
Labels: status: in-progress, type: new-feature, version: 5.5.1
