Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2019-10, with the labels that each got.

#924 Drop Oracle JDK from Travis CI #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.6.0

#927 Upgrade Spring Boot 2.2.0.RELEASE #925 Apply Spring Data Commons 2.2 #926
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
  terasoluna-gfw-parent/pom.xml
Labels: type: improvement, type: new-feature, version: 5.6.0

#922 fix convert of Boolean #846
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/el/ObjectToMapConverter.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/el/ObjectToMapConverterTest.java
Labels: version: 5.6.0
