Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2019-12, with the labels that each got.

#932 add innerElementClass attribute to pagination tag. #928
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/java/org/terasoluna/gfw/web/pagination/PaginationTag.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/main/resources/META-INF/terasoluna.tld
  terasoluna-gfw-common-libraries/terasoluna-gfw-web-jsp/src/test/java/org/terasoluna/gfw/web/pagination/PaginationTagTest.java
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/main/java/org/terasoluna/gfw/web/pagination/PaginationInfo.java
Labels: type: improvement

#934 update self defined libraries #933
  terasoluna-gfw-parent/pom.xml
Labels: type: new-feature, version: 5.6.0

#938 Upgrade Spring Boot 2.2.2.RELEASE #935
  terasoluna-gfw-common-libraries/terasoluna-gfw-common/src/test/java/org/terasoluna/gfw/common/sequencer/JdbcSequencerTest.java
  terasoluna-gfw-parent/pom.xml
Labels: type: improvement, type: new-feature, version: 5.6.0

#937 [5.5.x] Drop Oracle JDK from Travis CI #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: improvement, type: misc, version: 5.5.2

#939 [5.4.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.4.2

#940 [5.3.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.3.3

#941 [5.2.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.2.2

#942 [5.1.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.1.2

#943 [5.0.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 5.0.3

#944 [1.0.x] Fix Travis CI environment for Trusty #923
  .travis.yml
Labels: difficulity: mid, priority: high, type: misc, version: 1.0.7

#946 add dependency of java mail #945
  terasoluna-gfw-parent/pom.xml
Labels: version: 5.6.0

#948 not use static import that not needed #925
  terasoluna-gfw-common-libraries/terasoluna-gfw-web/src/test/java/org/terasoluna/gfw/web/pagination/PaginationInfoTest.java
Labels: type: improvement, version: 5.6.0
