Repository terasolunaorg/terasoluna-gfw, pull requests merged in 2020-06, with the labels that each got.

#981 remove exclude XML APIs #979
  terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
Labels: action: backport, type: bug, version: 5.6.0

#977 remove javax.mail #945 #975
  terasoluna-gfw-parent/pom.xml
Labels: action: functionaltest, action: migration-guide, type: oss-upgrade, version: 5.6.0

#982 exclude javax.activation-api, dependecy jakarta.activation-api #980
  terasoluna-gfw-dependencies/terasoluna-gfw-jpa-dependencies/pom.xml
Labels: type: oss-incompatible, version: 5.6.0

#978 Continue to support Commons FileUpload #976
  terasoluna-gfw-parent/pom.xml
Labels: type: improvement, version: 5.6.0
